language: c
compiler:
  - clang
  - gcc
before_script:
  - lsb_release -a
  - uname -a
  - env
  - sudo apt-get --no-install-recommends -qq -y build-dep surf
  - echo "CC = $CC" >> config.mk
script: make
notifications:
  email: false
